- name: Setup Redis Sentinel
  hosts: redis_servers
  become: true
  roles:
    - prometheus.prometheus.node_exporter
  vars_prompt:
    - name: ansible_user
      prompt: Ansible User
      private: false
    - name: ansible_ssh_private_key_file
      prompt: Ansible SSH Private Key File
      private: false
    - name: ansible_ssh_pass
      prompt: Ansible SSH Password
      private: true
    - name: redis_password
      prompt: Redis Password
      private: true
    - name: redis_maxmemory
      prompt: Redis Max Memory
      private: false
  tasks:
    - name: Install packages - 1
      dnf:
        name:
          - epel-release
          - https://rpms.remirepo.net/enterprise/remi-release-9.rpm
        state: present
        disable_gpg_check: true
    - name: Install packages - 2
      dnf:
        name:
          - '@redis:remi-7.2'
        state: present
        disable_gpg_check: true
    - name: Template redis.conf
      template:
        src: ../templates/redis.conf.j2
        dest: /etc/redis/redis.conf
        backup: true
    - name: Template sentinel.conf
      template:
        src: ../templates/sentinel.conf.j2
        dest: /etc/redis/sentinel.conf
        backup: true
    - name: Enable redis service
      systemd_service:
        name: redis
        state: restarted
        enabled: true
    - name: Enable redis-sentinel service
      systemd_service:
        name: redis-sentinel
        state: restarted
        enabled: true
    - name: Populate service facts
      service_facts:
    - name: Disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: false
      when: "'firewalld' in services"
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled
      register: selinux_result
    - name: Reboot if SELinux was changed
      ansible.builtin.reboot:
        reboot_timeout: 300
      when: selinux_result.changed